app/app/app/app_english/models.py
import os
from datetime import datetime

import pandas
from gtts import gTTS

from app.database import db


class Category(db.Model):
    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)

    def __repr__(self):
        return '<Category %r>' % self.name


class View(db.Model):
    __tablename__ = 'view'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)

    def __repr__(self):
        return '<View %r>' % self.name


class Words(db.Model):
    __tablename__ = 'words'
    __table_args__ = (
        db.UniqueConstraint("view_id", "word"),
    )
    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(255), nullable=False)
    translation = db.Column(db.String(255), nullable=False)
    url = db.Column(db.String(511), nullable=False)
    created_on = db.Column(db.DateTime(), default=datetime.utcnow)

    category_id = db.Column(db.Integer, db.ForeignKey('category.id', ondelete='CASCADE'), nullable=False)
    category = db.relationship('Category',  backref=db.backref('words', lazy=True))

    view_id = db.Column(db.Integer, db.ForeignKey('view.id', ondelete='CASCADE'), nullable=False)
    view = db.relationship('View',  backref=db.backref('views', lazy=True))

    def __repr__(self):
        return '<Words %r>' % self.word


def insert_data():
    """Обогощаем таблицу из данных xlsx"""
    db.create_all()
    direct = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'data\english.xlsx')
    music_directory = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'static\music')
    df_program = pandas.read_excel(direct, sheet_name='programm')
    df_other = pandas.read_excel(direct, sheet_name='other')
    view_dict = {}
    category_dict = {}
    words_in_base = []
    words = []

    view_all = db.session.query(View).all()
    if view_all:
        for elem in view_all:
            view_dict[elem.name] = elem.id

    category_all = db.session.query(Category).all()
    if category_all:
        for elem in category_all:
            category_dict[elem.name] = elem.id

    if "Программирование" not in category_dict.keys():
        new_category = Category(name="Программирование")
        db.session.add(new_category)
        db.session.commit()
        id_category_programm = new_category.id                  # возвращ id
        category_dict["Программирование"] = id_category_programm
    else:
        id_category_programm = category_dict["Программирование"]
    if "Остальное" not in category_dict.keys():
        new_category = Category(name="Остальное")
        db.session.add(new_category)
        db.session.commit()
        id_category_other = new_category.id                  # возвращ id
        category_dict["Остальное"] = id_category_other
    else:
        id_category_other = category_dict["Остальное"]

    words_all = db.session.query(Words).all()
    for element in words_all:
        el = tuple([element.view_id, element.word])
        words_in_base.append(el)

    for i, row in df_program.iterrows():
        if row["Вид"] not in view_dict.keys():
            new_view = View(name=row["Вид"])
            db.session.add(new_view)
            db.session.commit()
            id_view = new_view.id                              # возвращ id
            view_dict[row["Вид"]] = id_view
        else:
            id_view = view_dict[row["Вид"]]
        if tuple([view_dict[row["Вид"]], row["англ"]]) not in words_in_base:
            words.append(Words(word=row['англ'], translation=row['перев'], url='', category_id=id_category_programm, view_id=id_view))
            tts = gTTS(row['англ'], lang='en')
            tts.save(os.path.join(music_directory, f"{row['англ']}.mp3"))
            print(f'Добавлено {row["англ"]}')

    if words:
        db.session.add_all(words)
        db.session.commit()

    words = []
    for i, row in df_other.iterrows():
        if row["Вид"] not in view_dict.keys():
            new_view = View(name=row["Вид"])
            db.session.add(new_view)
            db.session.commit()
            id_view = new_view.id                              # возвращ id
            view_dict[row["Вид"]] = id_view
        else:
            id_view = view_dict[row["Вид"]]
        if tuple([view_dict[row["Вид"]], row["англ"]]) not in words_in_base:
            words.append(Words(word=row['англ'], translation=row['перев'], url='', category_id=id_category_other, view_id=id_view))
            tts = gTTS(row['англ'], lang='en')
            tts.save(os.path.join(music_directory, f"{row['англ']}.mp3"))
            print(f'Добавлено {row["англ"]}')
    if words:
        db.session.add_all(words)
        db.session.commit()


if __name__ == '__main__':
    db.create_all()
    insert_data()

app/app/app/models.py
from .database import db


class Feedback(db.Model):
    __tablename__ = 'feedback'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    topic = db.Column(db.String(255))
    email = db.Column(db.String(255))
    text = db.Column(db.Text)
    work = db.Column(db.Boolean, default=False)

    def __repr__(self):
        return '<feedback %r>' % self.name


if __name__ == '__main__':
    db.create_all()

app/app/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Email, Length


class FeedbackForm(FlaskForm):
    pass
    # name = PasswordField("Имя: ", validators=[DataRequired(), Length(min=4, max=255)])
    # topic = PasswordField("Тема: ", validators=[DataRequired(), Length(min=4, max=255)])
    # email = StringField("Email: ", validators=[Email()])
    # remember = BooleanField("Запомнить", default=False)
    # submit = SubmitField("Отправить")

app/app/app/__init__.py
from flask import Flask

from .database import db
import app.app_english.controllers as firstmodule

def create_app():
    app = Flask(__name__)
    app.config.from_object('config.BaseConfig')

    db.init_app(app)
    with app.test_request_context():
        db.create_all()

    app.register_blueprint(firstmodule.app_english, url_prefix='/english')
    return app

app/app/app/app_english/controllers.py
from flask import Flask, render_template, g, request, flash, redirect, url_for, abort, make_response, session
from flask import Blueprint

from app.database import db

from .models import View, Category, Words, insert_data


app_english = Blueprint('app_english', __name__, template_folder='templates', static_folder='static')


@app_english.route('/')
def english():
    return render_template('app_english/base_app_english.html')


@app_english.route('/programm')
@app_english.route('/programm/<int:page>', methods=['GET', 'POST'])
def english_words(page=1):
    all_words = db.session.query(Words).filter(Words.category_id == '1').paginate(page, 25, False)
    len_all_words = all_words.total
    now_page = all_words.page
    return render_template('app_english/english_words_programm.html', now_page=now_page, len_all_words=len_all_words, all_words=all_words)


@app_english.route('/other')
@app_english.route('/other/<int:page>', methods=['GET', 'POST'])
def english_words_other(page=1):
    all_words = db.session.query(Words).filter(Words.category_id == '2').paginate(page, 25, False)
    len_all_words = all_words.total
    now_page = all_words.page
    return render_template('app_english/english_words_other.html', now_page=now_page, len_all_words=len_all_words, all_words=all_words)


@app_english.route('/11')
def english2():
    insert_data()
    return render_template('app_english/base_app_english.html')

app/app/app/templates/about_me.html
{% extends 'base.html' %}

{% block link %}
{{ super() }}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='about.css') }}" >
{% endblock %}

{% block content %}
    <div class="container">
      <div class="title">DMITRIY PYTHON DEVELOPER</div>
      <div class="subtitle"> I LIKE TO DEVELOP AND SOLVE THE UNSOLVABLE </div>
    </div>

    <div class="content">
        <div class="card first">
            <h1>Начало блога</h1>
            <p class="date">08 июнь, 2020</p>
            <p class="text">
            Меня зовут Дмитрий. В данный момент являюсь junior+ python разработчиком. До разработки я окончил обучение
            СПБГУ по направлению "Землеустройство и кадастры" и "Управление Землепользованием". Работал в Росреестре в
            качестве инженера, Строительной компании - менеджером отдела сервиса, управляющей компании - менеджером
            рекламы и СМИ, МТС - специалист арендный отношений. Но после МТС мне захотелось свободы в рабочем процессе,
            отойти от монотонной и рутиной работы, заняться саморазвитием - подтянуть английский, разобраться в технологиях,
            освоить программирование и ... вот мой мини блог.</p>
        </div>
    </div>

{% endblock %}

app/app/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% block link %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}" >
	{% endblock %}
</head>
<body>
	{% block nav %}
    <div id="container">
		<ul id="menu">
			<li>
				<a id="logo" href="{{ url_for('main')}}"><img src="{{ url_for('static', filename='logo.png') }}" border="0" width="60" height="60" alt="Лого" /></a>
    		</li>
  			<li><a href="{{ url_for('app_english.english')}}">Английский язык</a>
				<ul>
					<li><a href="{{ url_for('app_english.english_words')}}">Программирование</a></li>
					<li><a href="{{ url_for('app_english.english_words_other')}}">Другое</a></li>
				</ul>
			</li>
			<li><a href="">Python</a></li>
			<li><a href="{{ url_for('about')}}">Об авторе</a>
				<ul>
					<li><a href="{{ url_for('feedback')}}">Обратная связь</a></li>
<!--					<li><a href="#">пусто</a></li>-->
<!--					<li><a href="#">пусто</a></li>-->
				</ul>
			</li>
		</ul>
	</div>
	{% endblock %}

	{% block content %}
	{% endblock %}

	<div id="footer">
		<p>© 2020 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных разрешено. Пользуйтесь на здоровье!</Пользуй></p>
	</p></div>
</body>
</html>

app/app/app/templates/feedback.html
{% extends 'base.html' %}

{% block link %}
{{ super() }}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='feedback.css') }}" >
{% endblock %}

{% block content %}

<div class="top">
  <p class="top_text">Контакты</p>
  <p>Для связи со мной используйте форму ниже. Все поля обязательны для заполнения.</p>
</div>

<!--<p>Так же можете написать мне</p>-->
<div id="form-main">
  {% for cat, msg in get_flashed_messages(True) %}
  <div class="flash {{cat}}">{{msg}}</div>
  {% endfor %}
  <div id="form-div">
    <form class="form" id="form1" method="post" action="{{ url_for('feedback') }}">
      {{ form.hidden_tag() }}
      <p class="name">
        <input name="name" type="text" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Имя" id="name" />
      </p>
      <p class="name">
        <input name="topic" type="text" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Тема" id="topic" />
      </p>
      <p class="email">
        <input name="email" type="text" class="validate[required,custom[email]] feedback-input" id="email" placeholder="Email" />
      </p>
      <p class="text">
        <textarea name="text" class="validate[required,length[6,300]] feedback-input" id="comment" placeholder="Текст"></textarea>
      </p>
      <div class="submit">
        <input type="submit" value="Отправить" id="button-blue"/>
        <div class="ease"></div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/app/app/templates/main.html
{% extends 'base.html' %}

{% block link %}
{{ super() }}
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}" >
{% endblock %}

{% block content %}

<main class='wrapper'>
  <div class='details'>
    <h1>Добро пожаловать на stePYstep!</h1>
    <h3>Личный сайт/микрблог </h3>
    <ul>
      <li>
        место для ссылки
      </li>
      <li>
        место для ссылки
      </li>
      <li>
        место для ссылки
      </li>
    </ul>
    <p>место для ссылки</p>
    <p>
      <strong>
        место для ссылки
      </strong>
    </p>
    <p>
      <strong>место для ссылки</strong>
    </p>
  </div>
  <div class='content howto'>
    <h2>Hа будущее 1</h2>

    <p>Hа будущее 1 текст</p>
    <h2>Hа будущее 2</h2>
    <p>Hа будущее 2 текст</p>
  </div>
  <hr>
  <div class='masonry'>
    <article class='box box-1'>
      <div class='content'>
        <h2>Content 1</h2>
      </div>
    </article>
    <article class='box box-2'>
      <div class='content'>
        <h2>Content 2</h2>
      </div>
    </article>
    <article class='box box-3'>
      <div class='content'>
        <h2>Content 3</h2>
      </div>
    </article>
    <article class='box box-4'>
      <div class='content'>
        <h2>Content 4</h2>
      </div>
    </article>
    <article class='box box-5'>
      <div class='content'>
        <h2>Content 5</h2>
      </div>
    </article>
    <article class='box box-6'>
      <div class='content'>
        <h2>Content 6</h2>
      </div>
    </article>
    <article class='box box-7'>
      <div class='content'>
        <h2>Content 7</h2>
      </div>
    </article>
    <article class='box box-8'>
      <div class='content'>
        <h2>Content 8</h2>
      </div>
    </article>
    <article class='box box-9'>
      <div class='content'>
        <h2>Content 9</h2>
      </div>
    </article>
    <article class='box box-10'>
      <div class='content'>
        <h2>Content 10</h2>
      </div>
    </article>
    <article class='box box-11'>
      <div class='content'>
        <h2>Content 11</h2>
      </div>
    </article>
    <article class='box box-12'>
      <div class='content'>
        <h2>Content 12</h2>
      </div>
    </article>
    <article class='box box-13'>
      <div class='content'>
        <h2>Content 13</h2>
      </div>
    </article>
    <article class='box box-14'>
      <div class='content'>
        <h2>Content 14</h2>
      </div>
    </article>
    <article class='box box-15'>
      <div class='content'>
        <h2>Content 15</h2>
      </div>
    </article>
    <article class='box box-16'>
      <div class='content'>
        <h2>Content 16</h2>
      </div>
    </article>
    <article class='box box-17'>
      <div class='content'>
        <h2>Content 17</h2>
      </div>
    </article>
    <article class='box box-18'>
      <div class='content'>
        <h2>Content 18</h2>
      </div>
    </article>
    <article class='box box-19'>
      <div class='content'>
        <h2>Content 19</h2>
      </div>
    </article>
    <article class='box box-20'>
      <div class='content'>
        <h2>Content 20</h2>
      </div>
    </article>
    <article class='box box-21'>
      <div class='content'>
        <h2>Content 21</h2>
      </div>
    </article>
    <article class='box box-22'>
      <div class='content'>
        <h2>Content 22</h2>
      </div>
    </article>
    <article class='box box-23'>
      <div class='content'>
        <h2>Content 23</h2>
      </div>
    </article>
    <article class='box box-24'>
      <div class='content'>
        <h2>Content 24</h2>
      </div>
    </article>
    <article class='box box-25'>
      <div class='content'>
        <h2>Content 25</h2>
      </div>
    </article>
  </div>
</main>

{% endblock %}